Python 3.14.0 (tags/v3.14.0:ebf955d, Oct  7 2025, 10:15:03) [MSC v.1944 64 bit (AMD64)] on win32
Enter "help" below or click "Help" above for more information.
>>> # Function definition
>>> def greater_than(x, y):
...     if x > y:
...         return True
...     else:
...         return False
... 
... 
...     
...     # Main section of the program
...     
...     a = 2
...     b = 3
... 
...     
...     result = greater_than(a, b)
... 
...     
>>> print("The statement" + str(a) + "is greatrer than" + str(b) + "is" + str(res)
